### ISSUE TITLE
Shared functions PPG and ECG

### ISSUE THREAD

**Issue by JanCBrammer** [neuropsychology/NeuroKit#166]
Some functions will eventually be used for both PPG and ECG. For example, `ecg_fixpeaks()` and `ecg_rate()`. Also the HRV-related functions can be used for PPG as well. How should we handle this? I guess duplicating functions is not ideal (i.e., maintaining identical `ecg_fixpeaks()` and `ppg_fixpeaks()`). For HRV-related stuff we could write a sub-package (i.e., alongside the `ecg` and `ppg` sub-packages)?

**Comment by DominiqueMakowski** [comment]
That's a good point, it's clearly not ideal to fully duplicate them, but on the other hand, it'd be weird to have a mix of `ecg_*` and `ppg_*` in the ppg pipeline. Moreover, the ppg user expects to find everything he needs under `ppg_*`. 

I think a possibility is to use aliasing and have `ppg_fixpeaks = ecg_fixpeaks` (we'd just have to format the docstring in ecg fixpeaks so that it also applies to the former). Another option would be to have:

```python
def ppg_fixpeaks(args):
    """Different docstring"""
     ecg_fixpeaks(args)
```
