### ISSUE TITLE
Scope and Dependencies?

### ISSUE THREAD

**Issue by JohnDoenut** [neuropsychology/NeuroKit#22]
Dear all,

### Dependencies
Neurokit 1 wrapped a lot of functionality of BioSPPy and MNE. Do we want to continue these dependencies in Neurokit 2 or implement our own (all this under the assumptions that less dependencies are a good thing)?

### Scope
I feel like including functionality for EEG/MEG is quite ambitious, especially since MNE already covers a lot of ground in this area. What would be our addition to MNE's functionality?
Alternatively, couldn't Neurokit 2 cover all biosignals that aren't EEG/MEG? That is, doing ECG, PPG, respiration etc., really well and make Neurokit 2 the go-to place for these signals while leaving EEG/MEG to MNE?

Curious about everyone's thoughts!

**Comment by DominiqueMakowski** [comment]
> (all this under the assumptions that less dependencies are a good thing)

I agree with this assumption, and it's sad that a "mild" dependency system doesn't exist (to me knowledge), similar to the 'SUGGESTS' in R, where you can have functions depending on some packages without them being mandatory dependencies. Now, in this particular case:

For biosppy, in NK1, many functions initially relied on it. In fact, neurokit1 was partly created out of biosspy's "limitations" (as its scope is more toward signal (pre)processing than features extraction). However, I ended up often re-implementing some of the functions to have more control over them.

So long story short, if we can make it without these dependencies, it'd be great. Now, we don't want to reinvent the wheel either, and nobody (at least me) has the time to reimplement some functions if they already exist and are well done 😁  So I'd say it's a matter of time and priority

We can start with using biosppy in order to rather focus on the missing features. And down the road, when we have time and all, we can also work on replacing our reliance on the dependencies by our own home-made great functions. 

This is allso for instance the case for `bioread`, from which a single specific function is used in only one function (`read_acqknowledge`) - still causing it to be a dependency. If possible, I'd have like to have our own reader, but I don't consider it as a priority... 

For mne, you make a good point. It's a heavy dependency, yet won't be used a lot in the short run (although initially, in NK1, I wanted to add support for some stuff not available in mne, in particular microstates and complexity). But you're right, maybe, - for now, we should remove it as a dependency and move the unique function that uses it somewhere else. And if further down the road we implement some awesome functions for M/EEG, we will eventually add it back if need be.
