### ISSUE TITLE
'bounds_R' option doesn't work for ecg_delineate using default method

### ISSUE THREAD

**Issue by johnnyzhang295** [neuropsychology/NeuroKit#363]
```
_,rpeaks = nk.ecg_peaks(ecg,sampling_rate=2000)
_, waves_peak = nk.ecg_delineate(ecg, rpeaks, sampling_rate=2000, show=True, show_type='bounds_R')
```

Results in this error being thrown:

_ValueError: No objects to concatenate_

But 'bounds_T', 'bounds_P', 'peaks' all work.

**Comment by Tam-Pham** [comment]
HI @johnnyzhang295, 

`show_type` argument basically indicates the type of delineated waves information showed in the plot.

The default method (which is `method="peak"`) is not currently returning the bounds_R information (the onsets and offsets of R-peaks) and hence, leading to the error. If you would like to have the bounds_R information, you can use either the the `cwt` or `dwt` method. 

Otherwise, to have all the delineated information plotted, you can set `show_type="all"`.

Hope that helps!

**Comment by johnnyzhang295** [comment]
Thanks!
