### ISSUE TITLE
Lyapunov exponents: tolerance default

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#566]
Hi there @CSchoel, when implementing [Rosenstein's method](https://archive.physionet.org/physiotools/lyapunov/RosensteinM93.pdf) of Lyapunov exponents, I was cross-checking the method of computing mean period as the minimum temporal separation of neighbors and was abit perplexed by this implementation from nolds here. 🤔 Could you share with us how you translated Rosenstein's documentation (granted that the description for this part in the original paper is very short, haha) to your implementation? Thanks!

_Originally posted by @zen-juen in https://github.com/neuropsychology/NeuroKit/pull/559#discussion_r738116251_

**Comment by CSchoel** [comment]
Hi @DominiqueMakowski and @zen-juen , that's a good question. Revisiting the code after such a long time, I have to admit that it could have done with a little more explanation. I looked it up and I think I remember what I did and why (and I noticed a few errors on my part):

Rosenstein suggests to use the "mean period as the reciprocal of the mean frequency of the power spectrum". The natural way to calculate this seemed to me to use a weighted arithmetic mean.

```python
f = np.fft.rfft(data, n * 2 - 1)
mf = np.fft.rfftfreq(n * 2 - 1) * np.abs(f)
mf = np.mean(mf[1:]) / np.sum(np.abs(f[1:]))
```
1. `rfftfreq` gives me the frequencies on the x-axis of the Fourier plot. I do not use the keyword argument `d` here, since we need the minimal temporal separation in numbers of datapoints and not in seconds.
2. I then multiply these frequencies with the absolute of the Fourier transform values to use them as weights for the weighted average. I think there is a small error here, because I seem to have missed the word "power" in the description of Rosenstein. Probably this should be `f**2` instead of `np.abs(f)`.
3. The next step again has an error. To build the weighted mean it should be `np.sum` instead of `np.mean`. I guess at the time of writing this I did not have good test cases or references to check whether the implementation was correct. :see_no_evil: 

Thanks very much for pointing this out. This was one of my main reasons for publishing nolds in the first place: I hoped that other people would find my errors and help me correct them. :laughing: 

A note on the implementation in Neurokit2: As far as I can see, the Neurokit implementation should be correct. However, I think dividing by `np.sum(w)` is redudant, since `w = psd["Power"] / np.sum(psd["Power"])` ensures that `w` will always sum up to one.

**Comment by zen-juen** [comment]
Hi @CSchoel thanks for getting back to us so quickly on this and for clarifying - this makes much more sense now and also reaffirms our implementation! I also agree with you on the use of a weighted arithmetic mean as well as the redundancy of   `np.sum(w)`, I realized it earlier too and now it's simply  `mean_freq = np.sum(psd["Power"] * psd["Frequency"]) / np.sum(psd["Power"])` right after extracting PSD 😄 

I have just one last question about the use of `max_tsep_factor = 0.25` (https://github.com/CSchoel/nolds/blob/51d8841db466143bf386324895e3c223c27553a5/nolds/measures.py#L240-L243), is it correct to say that this value is an arbitrary one to ensure the separation between two neighbours doesn't exceed some  threshold?

**Comment by CSchoel** [comment]
>  have just one last question about the use of max_tsep_factor = 0.25 (https://github.com/CSchoel/nolds/blob/51d8841db466143bf386324895e3c223c27553a5/nolds/measures.py#L240-L243), is it correct to say that this value is an arbitrary one to ensure the separation between two neighbours doesn't exceed some threshold?

Exactly. At other points in the code, I specifically calculate minimum data sizes, but this factor is just arbitrary. I think I introduced it, because I noticed that the calculated `min_tsep` was abnormally large for some of my test data (which in hindsight should have made me suspicious of the code for calculating it).

**Comment by zen-juen** [comment]
Right, thanks for confirming @CSchoel! @DominiqueMakowski We should probably keep in mind (+ search for) other methods that calculate minimum separation between neighbours. 😄 closing this issue for now then!
