### ISSUE TITLE
Add one time sponsoring

### ISSUE THREAD

**Issue by CReizner** [neuropsychology/NeuroKit#604]
Hello.
Is it possible for you to add one time sponsoring as an option?

**Comment by DominiqueMakowski** [comment]
Thanks for the suggestion, currently it doesn't seem possible through GitHub but we should look into it indeed :)

@Tam-Pham @zen-juen @JanCBrammer here are the supported platforms for sponsorship:

https://github.com/neuropsychology/NeuroKit/blob/d01111b9b82364d28da01c002e6cbfc45d9493d9/.github/FUNDING.yml#L1-L12

I think we could set up an account for NeuroKit on one of these. Patreon is a popular one but also only has subscriptions, otherwise, I'm looking at https://opencollective.com/ and it looks interesting: it's flexible and allows to manage the funds in an open and transparent way it seems. The Spyder IDE has an account: https://opencollective.com/spyder
