### ISSUE TITLE
Incorrectly marking T-wave as R-peak

### ISSUE THREAD

**Issue by paulbiegel** [neuropsychology/NeuroKit#752]
**Description**
I am analyzing a bunch of study data and I found that for many of them T-waves are marked as R-peaks if the T-wave has a higher amplitude compared to the R-peak, although there is hardly any noise within the signal or motion artifacts. This caused the beat-to-beat interval to be doubled in a almost all cases. Unfortunately I cannot add the data because of privacy.

**To Reproduce**
1. Load signal as numpy array
2. cleaned = ecg_clean_nk(signal, sampling_rate=frequency)
3. signals, info = ecg_peaks_nk(cleaned, sampling_rate=frequency, correct_artifacts=True, method=method)

**Expected behaviour**
Because it is such a clean ECG signal I would expect only true R-peaks to be marked and not that many false positives.

**Screenshots**
If applicable and useful, you can add screenshots by drag-and-dropping the images in the issue window.

**System Specifications**
Python 3.8, neurokit2 0.2.1

![output](https://user-images.githubusercontent.com/62943981/202641942-0a28fd2b-aab5-4bdf-84c4-87cd87961c1e.png)

**Comment by DominiqueMakowski** [comment]
Hi! I would perhaps try different peak-detection methods, as some might be more robust to these false positives. If not, then try more abrasive filtering (since the true R-peaks have a higher frequency than the T-waves, perhaps some filtering parameters can attenuate the latter)

However, most importantly, and assuming you have a similar-looking signal for all subjects (i.e., so that it's not a participant-specific issue), I would if possible adjust the recording method to one that maximizes R-peaks (lead I or lead II). I tend to personally use a modified lead II (one electrode under the left clavicle and 2 on each side at the ribs) which works well. Other setups can lead to other waves being magnified
