### ISSUE TITLE
Microstates

### ISSUE THREAD

**Issue by Winter-LabHub** [neuropsychology/NeuroKit#758]
Hi, I am testing out different microstate programs on MEG data. I saw your segment function can take MNE epoch objects but I can't get it to work. Do I need to flatten the dimensions, or is there another way to feed them in? At the moment I am simply putting in:
neurokit2.microstates_segment(epochs, sampling_rate=epochs.info['sfreq'])
Let me know if I am missing a step or something.

Thanks,
Matt

**Comment by danibene** [comment]
Hi @Winter-Bot would it be possible for you to share example data and the error you got?

**Comment by danibene** [comment]
Thanks @Winter-Bot I'll try to look into it this weekend!

**Comment by danibene** [comment]
@DominiqueMakowski do you have any thoughts here? I'm also confused as to how MNE epoch objects are used by NeuroKit, since several functions seem to assume continuous data, e.g. `eeg_gfp()` also is supposed to take an MNE epoch object:

https://github.com/neuropsychology/NeuroKit/blob/2fac6ebd7427d71b70fda7501893d1a0c478a8a7/neurokit2/eeg/eeg_gfp.py#L25-L28

But then the shape of the output doesn't correspond to the number of time points in each epoch: https://gist.github.com/danibene/11aaade571d3cec544ee360d36746734 

I think instead of returning the global field power corresponding to each timepoint, by using `axis=0` even when the input is an MNE epoch object, the mean and sum operations are done over the epochs rather than the channels:

https://github.com/neuropsychology/NeuroKit/blob/2fac6ebd7427d71b70fda7501893d1a0c478a8a7/neurokit2/eeg/eeg_gfp.py#L150

**Comment by DominiqueMakowski** [comment]
Mmh maybe it never got tested with epochs and the docstring entry was just copied 🙈 

https://github.com/neuropsychology/NeuroKit/blob/2fac6ebd7427d71b70fda7501893d1a0c478a8a7/neurokit2/eeg/eeg_gfp.py#L103

But this should transform epochs object into a dataframe, and since computing GFP is a row-wise operation it "should" have worked?

I know eeg is outside of your scope @danibene - sorry for that, I will try adding more testing to the EEG functions which hopefully will happen soon (I'll be soon analyzing some data with these functions too) 

+ I'm not even sure what we should return for `eeg_gfp()` if the input is epochs 🤔

**Comment by danibene** [comment]
@DominiqueMakowski 
> But this should transform epochs object into a dataframe, and since computing GFP is a row-wise operation it "should" have worked?

I think it doesn't work because it's a 3D NumPy array, and the input assumes a 2D array input. 

I'm not sure if concatenating the epochs would make sense for certain processing e.g. smoothing:
https://github.com/neuropsychology/NeuroKit/blob/2fac6ebd7427d71b70fda7501893d1a0c478a8a7/neurokit2/eeg/eeg_gfp.py#L138

Maybe looping over each epoch would be better? But I'm not an expert here, just my intuition if we don't have access to the original continuous data.
