### ISSUE TITLE
ECG simulation with RSP rate as parameter?

### ISSUE THREAD

**Issue by DominiqueMakowski** [neuropsychology/NeuroKit#81]
python implementation: https://github.com/jusjusjus/pyedr/blob/master/pyedr/synthetic.py (as a class, could be transformed into a function?) @Tam-Pham I wonder how it is different from the ECGSYN simulator (seems to be based on the same paper)

**Comment by Tam-Pham** [comment]
Yes, this python implementation is based on the same paper by McSharry (2003). However, perhaps due to the integration method that are being used, it does not seem to generate a signal as smooth as the one generated by `ecg_simulate` function in `neurokit`. 

ecg signal by `pyedr`:
<img width="776" alt="ecg2PNG" src="https://user-images.githubusercontent.com/47100701/72698089-85cd5a80-3b7d-11ea-851b-f131977150db.PNG">

ecg signal by `ecg_simulate` in neurokit (above is using a simpler model based on Daubechies wavelets, and below is using the ECGSYN dynamical model (McSharry et al., 2003):
<img width="773" alt="ecg1" src="https://user-images.githubusercontent.com/47100701/72698154-d2189a80-3b7d-11ea-8962-ae405799c59d.PNG">

However, one thing that I thought `ecg_simulate` in neurokit could add to its current implementation is to take into account the state of the respiration cycle (which the ecg simulation script in pyedr did).
