### ISSUE TITLE
Glucose regulation indices?

### ISSUE THREAD

**Issue by zen-juen** [neuropsychology/NeuroKit#829]
(after a loooooong hiatus away from neurokit.... 😅 )

I'm thinking of implementing some functions in neurokit for computing glucose regulation indices as I have some data from a flash glucose monitoring device (https://www.freestylelibre.com.au/freestyle-librelink.html) as part of my master's thesis. Was wondering if this is something that we'll want to incorporate as part of our features? 😄

**Comment by DominiqueMakowski** [comment]
Since it seems to be a new thing, strategically speaking, we should create a separate project that would be focused on that with all the dedicated keywords. That would increase its visibility and Googel-related discovery, and in the future nothing stops us from offloading some of its functionalities into NK

So I'd say you create a "SugarPhysio" or "PySugar" or "Glucopy" repo. We can make it heavily dependent on NK (it would be a specialized/betaVersion extension to NK). I think it would strongly benefit (e.g., for me lol) from a nice intro page about 1) what is this signal 2) how can we acquire it, 3) what does it look like (time domain and frequency signature) 4) what could it **potentially** be related to (cognition, disorders, physiological mechanisms and whatnot)
