### ISSUE TITLE
Customizing Processing Pipeline for Respiration

### ISSUE THREAD

**Issue by melisasaygin** [neuropsychology/NeuroKit#848]
I want to customize my own processing pipeline such that my only change is to the cleaning step. I first defined my_cleaning and checked that is actually works by itself. Then, when I try to define my_processing using the code provided, when I try to implement it to a raw respiration signal, it says that things are not defined (like as_vector). Is it because I didn't import the packages in the beginning? When I try, it says ''attempted relative import with no known parent package''. I hope you can help me as I need to resolve this. What should I do to make it run smoothly?

![image](https://github.com/neuropsychology/NeuroKit/assets/132986223/310f6bef-27d1-4659-ac60-f5655c0b3afd)

![image](https://github.com/neuropsychology/NeuroKit/assets/132986223/577310a0-1155-479e-9b19-0fa6deea4e52)

![image](https://github.com/neuropsychology/NeuroKit/assets/132986223/24eff846-3367-40da-bf1e-ca185b4264c4)

![image](https://github.com/neuropsychology/NeuroKit/assets/132986223/fd6d9cf6-f77e-4ac7-a272-e634a073767f)

**Comment by DominiqueMakowski** [comment]
This is because here, `as_vector` is a function from NK. When writing your own pipeline, you should prefix all the NK functions with `nk.` otherwise the program doesn't know where these come from.

Alternatively, you could *try* (although it is not recommended) to do a lazy import of all functions, using `from neurokit2 import *`
