### ISSUE TITLE
No figure displayed

### ISSUE THREAD

**Issue by ShantanuSen** [neuropsychology/NeuroKit#888]
https://github.com/neuropsychology/NeuroKit/blob/366583e1e22a4ea06a18e5e162675c2a33334a19/neurokit2/ppg/ppg_findpeaks.py#L226-L231

Description:
If I make the argument `show=True`, there is no figure displayed. I used this function as standalone.

Possible Solution:
after L231 we need to add `plt.show()`. For my case, it works. Should I make a PR after adding this line @DominiqueMakowski?

**Comment by DominiqueMakowski** [comment]
Hi @ShantanuSen, 

We removed the plt.show() because it creates problems in some setups. For instance, I have `%matplotlib inline` activated by default and so adding plt.show() would show the figure two times. 

I reckon you could simply either add `plt.show()` after the function call itself, or change your general settings to show it automatically? Not that I'm not very familiar with matplotlib so I don't know what specifically you need to change, but I just know that we removed the automatic plt.show from the functions insides on purpose ☺️

**Comment by ShantanuSen** [comment]
Hi @DominiqueMakowski,

Thanks for your reply. :)
